# Generated by Django 5.1 on 2024-12-15 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('botho', 'Botho'), ('dikgatlong green initiative', 'Dikgatlong Green Initiative'), ('dingwetsi tsa afrika', 'Dingwetsi Tsa Afrika')], default=django.utils.timezone.now, max_length=27),
            preserve_default=False,
        ),
    ]
